//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fines
    {
        public long Id { get; set; }
        public long UserID { get; set; }
        public long LoanId { get; set; }
        public double Amount { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string Name { get; set; }
    
        public virtual Loans Loans { get; set; }
    }
}
